site_name: My Data Science Notes

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: purple 

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: black
      accent: indigo
  
  font:
    text: Noto Sans
    code: Fira Code

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji 
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aravinds-arv
      name: arv on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aravinds-arv
      name: arv on LinkedIn
    - icon: fontawesome/brands/telegram
      link: https://t.me/aravinds_arv
      name: arv on t.me
  extra:
  analytics:
    provider: google
    property: G-8VG7KZ3TRG

repo_url: https://github.com/aravinds-arv/ds-notes
repo_name: aravinds-arv/ds-notes
edit_uri: edit/main/docs/

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - markdown-exec
  - glightbox
  - mkdocs-video:
      css_style:
          position: "absolute"
          width: "100%"
          height: "100%"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2023 Aravind S